# Generated by Django 3.0.6 on 2020-05-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('entry', models.CharField(max_length=1500)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
