# Generated by Django 3.0.6 on 2020-05-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zoneextra',
            name='name',
        ),
        migrations.AlterField(
            model_name='zoneextra',
            name='entry',
            field=models.TextField(),
        ),
    ]
