# Generated by Django 3.0.6 on 2020-08-25 09:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dns', '0002_auto_20200504_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.TextField()),
                ('value', models.TextField()),
                ('owners', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
