# Generated by Django 2.2.6 on 2019-10-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='api_url',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
