# Generated by Django 2.2.6 on 2019-10-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0003_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='sync',
            field=models.BooleanField(default=False),
        ),
    ]
