# Generated by Django 2.2.6 on 2019-10-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0004_image_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='syncing',
            field=models.DateTimeField(null=True),
        ),
    ]
