# Generated by Django 2.2.6 on 2019-10-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0005_host_syncing'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='alias',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='server',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
