# Generated by Django 2.2.6 on 2019-10-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0006_auto_20191017_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='aliases',
            field=models.TextField(null=True),
        ),
    ]
