# Generated by Django 3.0.4 on 2020-03-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0008_remove_image_aliases'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='protocol',
            field=models.CharField(choices=[('simplestreams', 'simplestreams'), ('lxd', 'lxd')], default='lxd', max_length=25),
        ),
    ]
