# Generated by Django 3.0.6 on 2020-11-19 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0010_host_monitoring_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='remove',
            field=models.BooleanField(default=False),
        ),
    ]
