# Generated by Django 2.2.6 on 2019-10-04 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0002_host_api_url'),
        ('container', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='container.Project'),
        ),
        migrations.AlterUniqueTogether(
            name='container',
            unique_together={('name', 'host')},
        ),
    ]
