# Generated by Django 2.2.6 on 2019-10-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0002_auto_20191004_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='state',
            field=models.TextField(null=True),
        ),
    ]
