# Generated by Django 2.2.6 on 2019-10-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0003_container_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='state_version',
            field=models.DateTimeField(null=True),
        ),
    ]
