# Generated by Django 2.2.6 on 2019-10-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0004_container_state_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='config',
            field=models.TextField(null=True),
        ),
    ]
