# Generated by Django 2.2.6 on 2019-10-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0005_container_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='config',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='state',
            field=models.TextField(blank=True, null=True),
        ),
    ]
