# Generated by Django 2.2.6 on 2019-10-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0006_auto_20191004_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='target_status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
