# Generated by Django 2.2.6 on 2019-10-17 09:05

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0009_hostkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostkey',
            name='private',
            field=fernet_fields.fields.EncryptedTextField(null=True),
        ),
    ]
