# Generated by Django 3.0.6 on 2020-05-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0010_auto_20191017_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
